version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - main

  api:
    image: social-authentication
    build:
      dockerfile: Dockerfile
      context: .
    command: bin/dj-run.sh
    volumes:
      - .:/app
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - main

networks:
  main:

# volumes:
#   pg_data:
